# This image generated by this Dockerfile requires nvidia-docker2
# It can only be run using the flag --gpu all

FROM nvidia/cuda:10.0-devel-ubuntu18.04

RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y \
    gcc-8 \
    g++-8 \
    git \
    python3 \
    python3-pip \
    libglu1-mesa \
    libxi-dev \
    libxmu-dev \
    libglu1-mesa-dev \
    freeglut3-dev \
    hdf5-tools \
    libboost-all-dev \
  && apt-get clean autoclean \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/* \
  && pip3 install \
    numpy \
    scipy \
    matplotlib \
    codepy \
    h5py==2.10.0 \
    pyopengl \
    docopt \
    biopython==1.75

RUN git clone --recurse-submodules https://github.com/inducer/pycuda.git && cd pycuda && python3 configure.py --cuda-enable-gl --no-use-shipped-boost && python3 setup.py install 

RUN pip3 install -e "git+https://github.com/koszullab/instagraal.git@no_opengl#egg=instagraal"


