# syntax=docker/dockerfile:1
# This image generated by this Dockerfile requires nvidia-docker2
# It can only be run using the flag --gpu all

FROM nvidia/cudagl:10.0-devel-ubuntu18.04

LABEL Name=instagraal Version=0.1.6

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub

RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y \
  gcc-8 \
  g++-8 \
  git \
  python3 \
  python3-pip \
  libglu1-mesa \
  libxi-dev \
  libxmu-dev \
  libglu1-mesa-dev \
  libjpeg-dev \
  zlib1g-dev \
  freeglut3-dev \
  hdf5-tools \
  libboost-all-dev \
  && apt-get clean autoclean \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/* \
  && pip3 install \
  numpy \
  scipy \
  matplotlib \
  codepy \
  h5py==2.10.0 \
  pyopengl \
  docopt \
  biopython==1.75 \
  MarkupSafe

WORKDIR /app

RUN git clone https://github.com/inducer/pycuda.git /root/pycuda && \
  cd /root/pycuda && \
  git reset --hard 38b7daf77f5549644d5cff5ccdd0d137ba738fde && \
  git submodule update --init --recursive && \
  python3 configure.py --cuda-enable-gl --no-use-shipped-boost && \
  python3 setup.py install 

RUN cd /app && pip3 install -e "git+https://github.com/koszullab/instagraal.git@no_opengl#egg=instagraal"


